theme: jekyll-theme-minimal
title: Vivek S
email: iamviveksrk at gmail dot com
description: Welcome to my Portfolio. 
blank_title: true
logo: /images/logo.jpeg

remote_theme: VivekSivaramakrishnan/minimal

color-scheme: dark
